default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  host: <%= ENV['DATABASE_HOST'] %>
  port: 3306
  pool: 5
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: computacao_distribuida_development

test:
  <<: *default
  database: computacao_distribuida_test

production:
  <<: *default
  database: computacao_distribuida_production
