default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root

development:
  <<: *default
  database: computacao_distribuida_development

test:
  <<: *default
  database: computacao_distribuida_test

production:
  <<: *default
  database: computacao_distribuida_production
